// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Link: typeof import('./components/Link.vue')['default']
    ObjForm: typeof import('./components/ObjForm.vue')['default']
  }
}

export {}
